name: base
channels:
  - defaults
  - pyviz 
dependencies:
  - conda
  - python=3.8
  - python.app
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2021.05=py38_0
  - anaconda-navigator==2.1.1
  - navigator-updater
  - hvplot
  - jupyter-panel-proxy
prefix: /opt/anaconda3
